### ISSUE TITLE
Is upstream integration OK with you?

### ISSUE THREAD

**Issue by xanderlent** [PJK/homebrew-libcbor#1]
In homebrew/homebrew-core#46071, @gvarisco attempted to upstream the libcbor formula, but it failed to meet the project's notability guidelines. Now that it's transitively used by OpenSSH (and close to meeting said guidelines) we're going to make another attempt at upstreaming it.

Would it be OK to integrate this formula upstream, under Homebrew's license?

I have a PR based on @gvarisco's work that properly credits both of you (`Co-authored-by:`) ready to go, but wanted to double-check before taking any action.

**Comment by PJK** [comment]
Hi @xanderlent, absolutely, go ahead!
